### ISSUE TITLE
HomePod models

### ISSUE THREAD

**Issue by drakebrian** [SeparateRecords/apple_device_identifiers#13]
Here are the model numbers for the current HomePod lineup.
```
{
    "HomePod": "AudioAccessory1,1",
    "HomePod": "AudioAccessory1,2",
    "HomePod Mini": "AudioAccessory5,1",
}
```
Thanks for the great resource!

**Comment by SeparateRecords** [comment]
Thanks!! Since it's JSON the keys need to be different - couldn't find a hardware difference between AudioAccessory1,1 and AudioAccessory1,2.

Maybe something like `"HomePod"` and `"HomePod (Revision)"`?

**Comment by drakebrian** [comment]
Good catch, I can't find any meaningful differences either. The model number for 1,1 is B238aAP while 1,2 is B238AP. 

I like `(Revision`) better than `(Unknown Model)` that I see elsewhere. I'll give contributing a go, thanks!
