### ISSUE TITLE
Apple Event, March 8 2022

### ISSUE THREAD

**Issue by SeparateRecords** [SeparateRecords/apple_device_identifiers#17]
My bet is new MacBook Air models, new Mac mini, and (maybe?) new iPads... let's see!

<img width="708" alt="image" src="https://user-images.githubusercontent.com/52195359/156877734-7ea01c2b-ae36-4b44-9d5a-f6f3258d263e.png">

**Comment by drakebrian** [comment]
Everything announced today:
- iPhone 13 Green
- iPhone Pro 13 Alpine Green
- iPhone SE (3rd generation)
- iPad Air M1 (5th generation)
- Mac Studio
- Studio Display

Guessing the iPhone 13/Pro won't get new identifiers

**Comment by SeparateRecords** [comment]
I think you're probably right, doubt the recolors will get unique IDs. 

As for the other devices, they're all distinct enough that we should be able to get data from Geekbench over the next couple of days. First thing reviewers do is stress test their devices!

**Comment by SeparateRecords** [comment]
https://twitter.com/stroughtonsmith/status/1501311104445829121

**Comment by SeparateRecords** [comment]
https://gist.github.com/adamawolf/3048717?permalink_comment_id=4095526#gistcomment-4095526

And with that, I think we know all the identifiers from this event!
