### ISSUE TITLE
URL Stopped Working

### ISSUE THREAD

**Issue by dale-courtney** [SeparateRecords/apple_device_identifiers#36]
I've been successfully downloading the list from here: 

`https://raw.githubusercontent.com/SeparateRecords/apple_device_identifiers/main/devices.json`

But today I'm getting the error: 
`404: Not Found`

**Comment by petarov** [comment]
The repository is named differently, so perhaps you have been using an older repository raw-link. The current one is https://raw.githubusercontent.com/clo4/apple_device_identifiers/main/devices.json

**Comment by dale-courtney** [comment]
@petarov Thank you for taking the time to respond with that new URL. I will update my code. 

Best,
Dale
